### ISSUE TITLE
Imports for Nodejs headless mode not working anymore on v0.25.0

### ISSUE THREAD

**Issue by finkton1** [enable3d/enable3d#243]
When trying to use new version of @ennabled3d/ammo-on-nodejs I get some issues.

Error: Cannot find module '[DIRECTORY]\@enable3d\ammo-on-nodejs\dist\index.js'. Please verify that the package.json has a valid "main" entry.

The culprit is:

`const { Physics, ServerClock } = require('@enable3d/ammo-on-nodejs');`

This works on v 0.24.0 however... I noticed in package.json for the lib references entrypoint of "/dist" - this no longer exists in v0.25.0

Referenced example is: [https://enable3d.io/examples/headless-mode.html](https://enable3d.io/examples/headless-mode.html)

**Comment by yandeu** [comment]
Thanks!

Has been fixed in v0.25.1
